spring:
  application:
    name: TripPop
  profiles:
    active: "local"

---
# local
server:
  port: 8080
spring:
  config:
    activate:
      on-profile: "local"
  datasource:
    url: ${POSTGRESQL_URL}
    username: ${POSTGRESQL_USERNAME}
    password: ${POSTGRESQL_PASSWORD}
  data:
    mongodb:
      uri: ${MONGODB_URI}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

---
# dev
server:
  port: 80
spring:
  config:
    activate:
      on-profile: "prod"