spring:
  application:
    name: TripPop
  mvc:
    problemdetails:
      enabled: true
  profiles:
    active: "local"
google:
  maps:
    api-key: ${GOOGLE_API_KEY}
---
# local
server:
  port: ${LOCAL_PORT:8080}
spring:
  config:
    activate:
      on-profile: "local"
  datasource:
    url: ${LOCAL_POSTGRESQL_URL}
    username: ${LOCAL_POSTGRESQL_USERNAME}
    password: ${LOCAL_POSTGRESQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

---
# dev
server:
  port: ${DEV_PORT:8080}
spring:
  config:
    activate:
      on-profile: "dev"
  datasource:
    url: ${DEV_POSTGRESQL_URL}
    username: ${DEV_POSTGRESQL_USERNAME}
    password: ${DEV_POSTGRESQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update